---
- hosts: k8smaster
  become: true
  tasks:
  - name: Reset Cluster
    command: "{{ item }}"
    with_items:
      - kubeadm reset -f
      - rm -fr /root/.kube

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --pod-network-cidr=10.244.0.0/16 --node-name k8s-master-ubuntu

  - name: Install canal-flannel CNI
    command: kubectl apply -f https://docs.projectcalico.org/manifests/canal.yaml
    environment: 
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - name: Fetch admin.conf to host
    fetch: 
      src: /etc/kubernetes/admin.conf
      dest: ./kubeconfig/
      flat: true

  - name: Install and enable host kubectl with proper KUBECONFIG
    become: false
    command: "{{ item }}"
    with_items:
      - mkdir -p /home/jasonlin/.kube
      - cp -v ./kubeconfig/admin.conf /home/jasonlin/.kube/admin.conf
    delegate_to: 127.0.0.1
