---
- hosts: k8snodes
  become: true
  tasks:
    - name: Reset Cluster
      command: "{{ item }}"
      with_items:
        - kubeadm reset -f
        - rm -fr /root/.kube

    - name: Set proper host name
      command: "hostnamectl set-hostname {{ inventory_hostname.split('.')[0] }}"

    - name: Sync join_command to node
      copy: 
        src: ./join-command
        dest: /tmp/join-command
        owner: root
        group: root
        mode: '0700'

    - name: Join cluster with token in join_command
      command: bash /tmp/join-command
